import { Song } from '../types';
import { parseDuration } from './duration';

export const PRESET_SONGS: { title: string; style: string; duration: string; artist: string }[] = [
  { title: "100 Anos", style: "FORRÓ", duration: "00:03:30", artist: "Victor & Leo" },
  { title: "A Dois Passos do Paraíso", style: "ROCK 80 BR", duration: "00:03:40", artist: "Blitz" },
  { title: "A Sombra da Maldade", style: "REGGAE", duration: "00:04:00", artist: "Cidade Negra" },
  { title: "Admirável Chip Novo", style: "ROCK 90 BR", duration: "00:04:00", artist: "Pitty" },
  { title: "Agamamou", style: "PAGODE", duration: "00:03:30", artist: "Araketu" },
  { title: "Ajoelha e Chora", style: "VANERÃO", duration: "00:03:00", artist: "Aviões do Forró" },
  { title: "All The Small Things", style: "ROCK", duration: "00:02:50", artist: "Blink-182" },
  { title: "Amante Profissional", style: "ROCK 80 BR", duration: "00:03:30", artist: "Herva Doce" },
  { title: "Amor de Chocolate", style: "POP BREGA", duration: "00:03:00", artist: "Naldo Benny" },
  { title: "ANNA JULIA", style: "ROCK 90 BR", duration: "00:03:30", artist: "Los Hermanos" },
  { title: "Anunciação", style: "FORRÓ", duration: "00:03:30", artist: "Alceu Valença" },
  { title: "Ar condicionado no 15", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Wesley Safadão" },
  { title: "Arranhão", style: "SERTANEJO UNIV", duration: "00:03:30", artist: "Henrique & Juliano" },
  { title: "Atrasadinha", style: "PAGODE", duration: "00:03:00", artist: "Felipe Araújo & Ferrugem" },
  { title: "Bad Moon Rising", style: "ROCK COUNTRY", duration: "00:02:20", artist: "Creedence Clearwater Revival" },
  { title: "BARQUINHO", style: "VANERÃO", duration: "00:02:30", artist: "Maysa" },
  { title: "Na Base do Beijo", style: "AXÉ", duration: "00:03:00", artist: "Ivete Sangalo" },
  { title: "Beautiful Day", style: "ROCK", duration: "00:04:05", artist: "U2" },
  { title: "Bebaça", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Marília Mendonça" },
  { title: "Beds Are Burning", style: "ROCK", duration: "00:04:15", artist: "Midnight Oil" },
  { title: "Biquini de Bolinha Amarelinha", style: "JOVEM GUARDA", duration: "00:02:30", artist: "Celly Campello" },
  { title: "Telefone mudo - Boate Azul - Saudades da minha terra - Evidências", style: "SERTANEJO RAIZ", duration: "00:10:00", artist: "Vários Artistas" },
  { title: "Bola de Sabão", style: "AXÉ", duration: "00:03:00", artist: "Babado Novo" },
  { title: "Born to be Wild", style: "ROCK", duration: "00:03:30", artist: "Steppenwolf" },
  { title: "BY THE WAY", style: "ROCK", duration: "00:03:35", artist: "Red Hot Chili Peppers" },
  { title: "Cant take my eyes", style: "POP 80", duration: "00:03:30", artist: "Frankie Valli" },
  { title: "Celebration", style: "DISCO 80", duration: "00:04:00", artist: "Kool & The Gang" },
  { title: "Cerveja de Garrafa", style: "PAGODE", duration: "00:03:00", artist: "Atitude 67" },
  { title: "Cheia de Manias", style: "PAGODE", duration: "00:04:00", artist: "Raça Negra" },
  { title: "China Véia", style: "VANERÃO", duration: "00:03:00", artist: "Aviões do Forró" },
  { title: "Chopis Centis", style: "ROCK 90 BR", duration: "00:02:30", artist: "Mamonas Assassinas" },
  { title: "Ciume", style: "ROCK 80 BR", duration: "00:03:00", artist: "Ultraje a Rigor" },
  { title: "Colo de Menina", style: "FORRÓ", duration: "00:03:00", artist: "Rastapé" },
  { title: "Come Together", style: "ROCK", duration: "00:04:20", artist: "The Beatles" },
  { title: "Crazy in Love", style: "POP", duration: "00:03:55", artist: "Beyoncé" },
  { title: "Crazy Little Thing", style: "POP 80", duration: "00:02:45", artist: "Queen" },
  { title: "Dança da Cordinha", style: "AXÉ ENTRETENIMENTO", duration: "00:03:00", artist: "Eliana" },
  { title: "Dance Monkey", style: "POP", duration: "00:03:30", artist: "Tones and I" },
  { title: "Dancing Days", style: "POP 80 BR", duration: "00:03:00", artist: "As Frenéticas" },
  { title: "Danza Kuduro", style: "POP BREGA", duration: "00:03:20", artist: "Don Omar & Lucenzo" },
  { title: "Daqui Pra Sempre", style: "SERTANEJO UNIV", duration: "00:03:30", artist: "Jota Quest" },
  { title: "Descobridor Dos Sete Mares", style: "POP 80 BR", duration: "00:04:00", artist: "Tim Maia" },
  { title: "Do Fundo da Grota", style: "VANERÃO", duration: "00:03:30", artist: "Baitaca" },
  { title: "Do Seu Lado", style: "ROCK 90 BR", duration: "00:04:00", artist: "Jota Quest" },
  { title: "Dont Let Me Down", style: "ROCK", duration: "00:03:30", artist: "The Chainsmokers & Daya" },
  { title: "Don't Start Now", style: "POP", duration: "00:03:03", artist: "Dua Lipa" },
  { title: "Dont stop me now", style: "POP ROCK", duration: "00:03:00", artist: "Dua Lipa" },
  { title: "Era Um Garoto Que Como Eu", style: "JOVEM GUARDA", duration: "00:04:00", artist: "Engenheiros do Hawaii" },
  { title: "Erro gostoso", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Simone & Simaria" },
  { title: "Erva Venenosa", style: "ROCK 80 BREGA BR", duration: "00:03:00", artist: "Rita Lee" },
  { title: "Esperando na Janela - Falamansa", style: "FORRÓ", duration: "00:03:30", artist: "Falamansa" },
  { title: "Esperando na janela - Cogumelos de plutão", style: "SERTANEJO RAIZ", duration: "00:03:20", artist: "Cogumelo de Plutão" },
  { title: "Esquema Preferido", style: "PISADINHA", duration: "00:03:00", artist: "Tarcísio do Acordeon & Vitor Fernandes" },
  { title: "Eu Quero amor, Você", style: "JOVEM GUARDA", duration: "00:03:10", artist: "The Fevers" },
  { title: "Eu sou terrível", style: "JOVEM GUARDA", duration: "00:02:30", artist: "Roberto Carlos" },
  { title: "Eva - Alô Paixão - Beleza rara", style: "AXÉ", duration: "00:10:00", artist: "Banda Eva" },
  { title: "Exagerado", style: "ROCK 80 BR", duration: "00:03:30", artist: "Cazuza" },
  { title: "Falta Você", style: "PAGODE", duration: "00:03:30", artist: "Thiaguinho" },
  { title: "Feche os olhos", style: "JOVEM GUARDA", duration: "00:03:00", artist: "Forró do Muído" },
  { title: "Fio de Cabelo", style: "SERTANEJO RAIZ", duration: "00:03:30", artist: "Chitãozinho & Xororó" },
  { title: "Flowers", style: "POP", duration: "00:03:20", artist: "Miley Cyrus" },
  { title: "Fogo e Paixão", style: "BREGA", duration: "00:04:00", artist: "Wando" },
  { title: "Footloose", style: "POP 80", duration: "00:03:50", artist: "Kenny Loggins" },
  { title: "Girls just want to have fun", style: "POP 80", duration: "00:03:55", artist: "Cyndi Lauper" },
  { title: "Happy", style: "POP", duration: "00:03:50", artist: "Pharrell Williams" },
  { title: "Have You Ever Seen The Rain", style: "POP ROCK", duration: "00:02:40", artist: "Creedence Clearwater Revival" },
  { title: "I still havent found", style: "ROCK", duration: "00:04:30", artist: "U2" },
  { title: "I want to break free", style: "ROCK", duration: "00:04:20", artist: "Queen" },
  { title: "I Will Survive", style: "DISCO 80", duration: "00:04:00", artist: "Gloria Gaynor" },
  { title: "Its a Heartache", style: "POP ROCK", duration: "00:03:30", artist: "Bonnie Tyler" },
  { title: "Jambalaya", style: "ROCK COUNTRY", duration: "00:03:00", artist: "Blue Ridge Rangers" },
  { title: "Just Cant Get Enought", style: "POP 80", duration: "00:03:44", artist: "Depeche Mode" },
  { title: "Lapada Dela", style: "PAGODE", duration: "00:02:50", artist: "Saia Rodada" },
  { title: "Like a Prayer", style: "POP", duration: "00:05:42", artist: "Madonna" },
  { title: "Listen to the music", style: "ROCK COUNTRY", duration: "00:03:49", artist: "The Doobie Brothers" },
  { title: "Little Respect", style: "POP 80", duration: "00:03:32", artist: "Erasure" },
  { title: "Living on a prayer", style: "ROCK", duration: "00:04:10", artist: "Bon Jovi" },
  { title: "Losing My Religion", style: "ROCK", duration: "00:04:28", artist: "R.E.M." },
  { title: "Love me to Times", style: "ROCK", duration: "00:03:16", artist: "The Doors" },
  { title: "Macarena", style: "POP BREGA", duration: "00:03:51", artist: "Los Del Rio" },
  { title: "Macetando", style: "AXÉ", duration: "00:02:30", artist: "MC Loma e as Gêmeas Lacrações" },
  { title: "Vou pra SC - Maria Tcha Tcha Tcha", style: "VANERÃO", duration: "00:09:00", artist: "Vários Artistas" },
  { title: "Menina linda", style: "JOVEM GUARDA", duration: "00:03:00", artist: "Luan Santana" },
  { title: "O Menino da Porteira", style: "SERTANEJO RAIZ", duration: "00:03:30", artist: "Sérgio Reis" },
  { title: "Meu coração deu PT", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Wesley Safadão" },
  { title: "Meu erro", style: "ROCK 80 BR", duration: "00:03:20", artist: "Os Paralamas do Sucesso" },
  { title: "Morto Muito Louco", style: "AXÉ ENTRETENIMENTO", duration: "00:02:30", artist: "Mamonas Assassinas" },
  { title: "Moves Like Jagger", style: "POP", duration: "00:03:21", artist: "Maroon 5 feat. Christina Aguilera" },
  { title: "Mulher de Fases", style: "ROCK 90 BR", duration: "00:03:00", artist: "Raimundos" },
  { title: "Mulherada", style: "PAGODE", duration: "00:03:00", artist: "Mr. Catra" },
  { title: "Não, não vou", style: "SERTANEJO UNIV", duration: "00:02:30", artist: "Mari Fernandez" },
  { title: "Não Quero Dinheiro", style: "POP 80 BR", duration: "00:03:00", artist: "Tim Maia" },
  { title: "Não Sei", style: "ROCK 80 BR", duration: "00:03:00", artist: "Marisa Monte" },
  { title: "Nosso Xote", style: "FORRÓ", duration: "00:03:00", artist: "Falamansa" },
  { title: "Nova York", style: "SERTANEJO RAIZ", duration: "00:03:00", artist: "Christian & Ralf" },
  { title: "O pão da minha prima", style: "ROCK 90 BR", duration: "00:03:00", artist: "Aviões do Forró" },
  { title: "Obladi Oblada", style: "ROCK", duration: "00:03:08", artist: "The Beatles" },
  { title: "Oh! Chuva", style: "FORRÓ", duration: "00:03:00", artist: "Falamansa" },
  { title: "Onda Onda", style: "AXÉ ENTRETENIMENTO", duration: "00:03:00", artist: "Tchakabum" },
  { title: "OPEN YOUR EYES", style: "ROCK", duration: "00:05:41", artist: "Snow Patrol" },
  { title: "OTHERSIDE", style: "ROCK", duration: "00:04:15", artist: "Red Hot Chili Peppers" },
  { title: "País tropical - Arerê - Canibal", style: "AXÉ", duration: "00:09:00", artist: "Vários Artistas" },
  { title: "Palhaça", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Nelson Gonçalves" },
  { title: "Parada Louca", style: "PISADINHA", duration: "00:03:00", artist: "Henrique & Juliano" },
  { title: "Pé Na Areia", style: "PAGODE", duration: "00:03:00", artist: "Diogo Nogueira" },
  { title: "Pescador de Ilusões", style: "ROCK 80 BR", duration: "00:04:30", artist: "O Rappa" },
  { title: "Pintura Intima", style: "ROCK 80 BREGA BR", duration: "00:03:00", artist: "Kid Abelha" },
  { title: "Pipoco", style: "SERTANEJO UNIV", duration: "00:02:30", artist: "Ana Castela, Melody & DJ Chris No Beat" },
  { title: "Proibida Pra Mim", style: "ROCK 90 BR", duration: "00:03:00", artist: "Charlie Brown Jr." },
  { title: "Proud Mary", style: "POP ROCK", duration: "00:03:07", artist: "Creedence Clearwater Revival" },
  { title: "Psycho Killer", style: "POP ROCK", duration: "00:04:20", artist: "Talking Heads" },
  { title: "Rádio Blá", style: "ROCK 80 BR", duration: "00:03:00", artist: "Lobão" },
  { title: "Radio ga ga", style: "POP ROCK", duration: "00:05:48", artist: "Queen" },
  { title: "Rádio Pirata", style: "ROCK 80 BR", duration: "00:04:00", artist: "RPM" },
  { title: "Razões e Emoções", style: "ROCK 90 BR", duration: "00:03:00", artist: "NX Zero" },
  { title: "Reggae Na Casa Amarela", style: "REGGAE", duration: "00:03:00", artist: "Natiruts" },
  { title: "Rivers Of Babylon", style: "ROCK", duration: "00:04:00", artist: "Boney M." },
  { title: "Roadhouse Blues", style: "ROCK", duration: "00:04:04", artist: "The Doors" },
  { title: "Robocop Gay", style: "BREGA", duration: "00:02:30", artist: "Mamonas Assassinas" },
  { title: "Rock and Roll All Nite", style: "ROCK", duration: "00:02:48", artist: "Kiss" },
  { title: "Roxanne", style: "ROCK", duration: "00:03:12", artist: "The Police" },
  { title: "Salão de Festa a Vapor", style: "REGGAE", duration: "00:03:00", artist: "Zeca Baleiro" },
  { title: "Sandra Rosa Madalena", style: "BREGA", duration: "00:03:00", artist: "Sidney Magal" },
  { title: "Saudade da Minha Terra", style: "SERTANEJO RAIZ", duration: "00:03:00", artist: "Chitãozinho & Xororó" },
  { title: "Sonífera Ilha", style: "ROCK 80 BR", duration: "00:03:00", artist: "Titãs" },
  { title: "Sorte que ce beija bem", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Maiara & Maraisa" },
  { title: "Stand By Me", style: "ROCK", duration: "00:02:55", artist: "Ben E. King" },
  { title: "Suspicious Minds", style: "ROCK", duration: "00:04:22", artist: "Elvis Presley" },
  { title: "Sweet Dreams", style: "POP 80", duration: "00:03:36", artist: "Eurythmics" },
  { title: "Tô Rocheda", style: "PISADINHA", duration: "00:02:30", artist: "Os Barões da Pisadinha" },
  { title: "Take on me", style: "POP 80", duration: "00:03:45", artist: "a-ha" },
  { title: "Tempo perdido", style: "ROCK 80 BR", duration: "00:04:00", artist: "Legião Urbana" },
  { title: "The heat is on", style: "POP 80", duration: "00:03:45", artist: "Glenn Frey" },
  { title: "Time", style: "ROCK", duration: "00:06:53", artist: "Pink Floyd" },
  { title: "Toda forma de amor", style: "ROCK 80 BR", duration: "00:03:00", artist: "Lulu Santos" },
  { title: "Treasure", style: "POP", duration: "00:02:56", artist: "Bruno Mars" },
  { title: "Tutti Frutti", style: "ROCK", duration: "00:02:25", artist: "Little Richard" },
  { title: "Twist And Shout", style: "ROCK", duration: "00:02:33", artist: "The Beatles" },
  { title: "Vagabundo eu Confesso", style: "REGGAE", duration: "00:03:00", artist: "Zé Ramalho" },
  { title: "Vai lá em casa hoje", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "George Henrique & Rodrigo" },
  { title: "Voando pro Pará", style: "SERTANEJO UNIV", duration: "00:03:00", artist: "Pinduca" },
  { title: "Watermelon Sugar", style: "POP", duration: "00:02:54", artist: "Harry Style" },
  { title: "Whisky a gogo", style: "ROCK 80 BREGA BR", duration: "00:03:45", artist: "Roupa Nova" },
  { title: "Who Stop The Rain", style: "ROCK", duration: "00:02:28", artist: "Creedence Clearwater Revival" },
  { title: "Wish You Were Here", style: "ROCK", duration: "00:05:35", artist: "Pink Floyd" },
  { title: "WITH OR WITHOUT YOU", style: "ROCK", duration: "00:04:56", artist: "U2" },
  { title: "Yellow Submarine", style: "ROCK", duration: "00:02:38", artist: "The Beatles" },
  { title: "YMCA", style: "DISCO 80", duration: "00:04:47", artist: "Village People" },
  { title: "You Shock Me All Night Long", style: "ROCK", duration: "00:03:30", artist: "AC/DC" },
  { title: "Your Love", style: "ROCK", duration: "00:03:40", artist: "The Outfield" },
  { title: "Zona de Perigo", style: "PAGODE", duration: "00:02:50", artist: "Léo Santana" },
  { title: "Nosso Primeiro Beijo", style: "PAGODE", duration: "00:02:48", artist: "Gloria Groove" },
  { title: "Coração Partido", style: "PAGODE", duration: "00:03:15", artist: "Grupo Menos é Mais" },
  { title: "Última Noite", style: "FUNK", duration: "00:02:31", artist: "Nattan e Leo Foguete" },
  { title: "Beautiful Things", style: "POP", duration: "00:03:00", artist: "Benson Boone" },
  { title: "Envolver", style: "FUNK", duration: "00:03:13", artist: "Anitta" },
  { title: "Valerie", style: "POP ROCK", duration: "00:03:47", artist: "Amy Winehouse" },
  { title: "Não deixe o samba morrer", style: "SAMBA", duration: "00:04:26", artist: "Alcione" },
  { title: "Hey Ya", style: "POP", duration: "00:03:55", artist: "Outkast" },
  { title: "Everybody", style: "POP", duration: "00:04:57", artist: "Madonna" },
  { title: "Tô voltando pra ficar", style: "SERTANEJO", duration: "00:03:15", artist: "Zé Neto & Cristiano" },
  { title: "É problema meu", style: "SERTANEJO", duration: "00:03:46", artist: "Tchê Garotos" },
  { title: "Bebo pa carai", style: "SERTANEJO", duration: "00:03:21", artist: "Gino & Geno" },
  { title: "Jeito sexy", style: "POP", duration: "00:02:40", artist: "Fat Famiy" },
  { title: "Wanna be", style: "POP", duration: "00:02:52", artist: "Spice Girls" },
  { title: "Get Lucky", style: "POP", duration: "00:02:30", artist: "Daft Punk" },
  { title: "Ai Ai Ai (Vanessa da Mata)", style: "POP ROCK", duration: "00:03:58", artist: "Vanessa da Mata" },
  { title: "Encontrar alguém", style: "POP ROCK", duration: "00:03:46", artist: "Jota Quest" },
  { title: "Na moral", style: "POP ROCK", duration: "00:04:00", artist: "Jota Quest" },
  { title: "A Francesa", style: "ROCK 80 BR", duration: "00:04:00", artist: "Marina Lima" },
  { title: "Menina Veneno", style: "ROCK 80 BR", duration: "00:04:41", artist: "Ritchie" },
];

export const getInitialSongs = (): Song[] => {
  return PRESET_SONGS.map(s => ({
    id: crypto.randomUUID(),
    title: s.title,
    artist: s.artist,
    duration: parseDuration(s.duration),
    style: s.style,
    driveLink: '',
    fileType: 'other'
  }));
};
